general:
  start_date: 2020-01-01
  end_date: 2020-12-31
  multipatch: false

pollinator:
  solitary_trait_file: example/solitary_pollinator_traits.csv
  colony_trait_file: example/colony_pollinator_traits.csv

  default_solitary:
    init_density: 1
    t_opt: 1

  default_colony:
    init_density: 1